'use client'
import { useState, useRef } from 'react'
import { Camera, Upload, Leaf, AlertCircle, Loader, X, Download, RotateCcw, CheckCircle, Droplets, Sun, FlaskConical, Shield, Microscope } from 'lucide-react'

interface PlantResult {
  name: string
  scientific_name: string
  confidence: number
  family: string
  description: string
  medicinal_uses: string[]
  preparation: string
  safety: string
  is_toxic: boolean
}

function downloadPlantPDF(result: PlantResult) {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
  <title>Dr. Gideon Afolabi — Plant Analysis Report</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}body{font-family:Georgia,serif;color:#0d1f12}
    .header{background:linear-gradient(135deg,#0a3d1f,#145a2e);color:white;padding:40px;display:flex;justify-content:space-between;align-items:center}
    .brand h1{font-size:22px;color:#ffd700;margin-bottom:4px}.brand p{font-size:11px;color:rgba(255,255,255,0.6);text-transform:uppercase;letter-spacing:2px}
    .conf{background:rgba(255,215,0,0.2);border:1px solid rgba(255,215,0,0.4);border-radius:12px;padding:14px 20px;text-align:center}
    .conf-num{font-size:36px;font-weight:900;color:#ffd700;line-height:1}.conf-lbl{font-size:10px;color:rgba(255,255,255,0.6);text-transform:uppercase;letter-spacing:2px;margin-top:2px}
    .content{padding:40px}.plant-name{font-size:32px;font-weight:900;color:#0a3d1f;margin-bottom:4px}
    .plant-sci{font-size:14px;color:#888;font-style:italic;margin-bottom:4px}.plant-fam{font-size:12px;color:#22a050;font-weight:600;margin-bottom:20px}
    .desc{background:#f8fff4;border:1px solid rgba(34,160,80,0.2);border-radius:12px;padding:16px;font-size:13px;color:#444;line-height:1.7;margin-bottom:24px}
    .sec{font-size:16px;font-weight:bold;color:#0a3d1f;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #ffd700}
    .uses{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:24px}
    .use{display:flex;align-items:center;gap:8px;background:#f0faf0;border:1px solid rgba(34,160,80,0.2);border-radius:8px;padding:8px 12px;font-size:12px;color:#145a2e}
    .dot{width:8px;height:8px;border-radius:50%;background:#22a050;flex-shrink:0}
    .prep{background:linear-gradient(135deg,#0a3d1f,#145a2e);border-radius:12px;padding:20px;margin-bottom:20px}
    .prep p{color:rgba(255,255,255,0.85);font-size:13px;line-height:1.7}
    .safety-box{background:#fffbeb;border:1px solid #fde68a;border-radius:12px;padding:16px}
    .safety-box p{font-size:12px;color:#92400e;line-height:1.6}
    .footer{background:#f8fff4;border-top:1px solid rgba(34,160,80,0.2);padding:20px 40px;margin-top:30px;font-size:11px;color:#888}
  </style></head><body>
  <div class="header">
    <div class="brand"><h1>🌿 Dr. Gideon Afolabi Wellness</h1><p>Plant Identification Report · ${date}</p></div>
    <div class="conf"><div class="conf-num">${result.confidence}%</div><div class="conf-lbl">AI Confidence</div></div>
  </div>
  <div class="content">
    <div class="plant-name">${result.name}</div>
    <div class="plant-sci">${result.scientific_name}</div>
    ${result.family ? `<div class="plant-fam">Family: ${result.family}</div>` : ''}
    ${result.is_toxic ? `<div style="background:#fef2f2;border:1px solid #fecaca;border-radius:12px;padding:14px;margin-bottom:20px;color:#dc2626;font-size:12px;font-weight:bold">⚠️ Warning: This plant may be toxic. Do not consume without expert verification.</div>` : ''}
    <div class="desc">${result.description}</div>
    <div class="sec">Medicinal Uses</div>
    <div class="uses">${result.medicinal_uses.map(u => `<div class="use"><div class="dot"></div>${u}</div>`).join('')}</div>
    <div class="sec">Preparation Guide</div>
    <div class="prep"><p>${result.preparation}</p></div>
    <div class="sec">Safety Information</div>
    <div class="safety-box"><p>⚠️ ${result.safety}</p></div>
  </div>
  <div class="footer">
    <p><strong>Disclaimer:</strong> This plant identification report is generated by AI and is for educational purposes only. Always consult a qualified herbalist before using any plant medicinally.</p>
    <p style="margin-top:6px">Dr. Gideon Afolabi Wellness · Herbal Wisdom Reviews · © ${new Date().getFullYear()}</p>
  </div></body></html>`
  const win = window.open('', '_blank')
  if (win) { win.document.write(html); win.document.close(); setTimeout(() => { win.print() }, 500) }
}

const medicinalDB: Record<string, Partial<PlantResult>> = {
  'aloe vera': { description: 'A succulent plant known worldwide for its healing gel, used medicinally for thousands of years.', medicinal_uses: ['Wound healing', 'Sunburn relief', 'Skin moisturizing', 'Digestive support'], preparation: 'Cut a leaf, extract the gel, apply directly to skin. For internal use, dilute 1 tbsp gel in water.', safety: 'Avoid ingesting latex layer. Not recommended during pregnancy.', is_toxic: false },
  'lavender': { description: 'Aromatic herb widely used for relaxation and skin healing, native to the Mediterranean.', medicinal_uses: ['Anxiety relief', 'Sleep support', 'Headache relief', 'Antiseptic'], preparation: 'Use as essential oil in diffuser, or make lavender tea with 1 tsp dried flowers in hot water.', safety: 'Generally safe. Avoid undiluted essential oil on skin.', is_toxic: false },
  'peppermint': { description: 'Cooling herb used globally for digestive and pain relief.', medicinal_uses: ['Headache relief', 'Digestive aid', 'Nausea relief', 'Energy boost'], preparation: 'Brew 1 tbsp leaves as tea. Apply diluted oil to temples for headache.', safety: 'Avoid near infants. Do not ingest oil directly.', is_toxic: false },
  'chamomile': { description: 'Gentle calming herb from the daisy family with a soothing apple-like scent.', medicinal_uses: ['Sleep support', 'Anxiety relief', 'Digestive aid', 'Anti-inflammatory'], preparation: 'Steep 1 tbsp dried flowers in hot water 5 min. Drink 2-3 cups daily.', safety: 'May cause allergy in those sensitive to ragweed.', is_toxic: false },
  'rosemary': { description: 'Aromatic Mediterranean herb with cognitive and circulatory benefits.', medicinal_uses: ['Memory support', 'Hair growth', 'Circulation', 'Antioxidant'], preparation: 'Brew as tea. Apply diluted oil to scalp for hair growth.', safety: 'Avoid large doses in pregnancy. Generally safe in culinary use.', is_toxic: false },
}

export default function PlantIdentifierPage() {
  const [image, setImage] = useState<string | null>(null)
  const [file, setFile] = useState<File | null>(null)
  const [result, setResult] = useState<PlantResult | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0]
    if (!f) return
    setFile(f); setResult(null); setError(null)
    const reader = new FileReader()
    reader.onload = (ev) => setImage(ev.target?.result as string)
    reader.readAsDataURL(f)
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    const f = e.dataTransfer.files?.[0]
    if (f && f.type.startsWith('image/')) {
      setFile(f); setResult(null); setError(null)
      const reader = new FileReader()
      reader.onload = (ev) => setImage(ev.target?.result as string)
      reader.readAsDataURL(f)
    }
  }

  const identifyPlant = async () => {
    if (!file) return
    setLoading(true); setError(null)
    try {
      // Route through our own server-side proxy (/api/identify) to avoid CORS.
      // The proxy forwards the image to PlantNet from the server — no browser CORS restriction.
      const formData = new FormData()
      formData.append('images', file)

      const res = await fetch('/api/identify', {
        method: 'POST',
        body: formData,
      })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data?.error || data?.message || `Server error ${res.status}`)
      }

      const top = data.results?.[0]
      if (!top) throw new Error('No plant could be identified. Try a clearer, well-lit photo.')

      // Extract all useful fields from response
      const commonNames: string[] = top.species?.commonNames || []
      const plantName = commonNames[0] || top.species?.scientificNameWithoutAuthor || 'Unknown Plant'
      const scientific = top.species?.scientificNameWithoutAuthor || ''
      const family = top.species?.family?.scientificNameWithoutAuthor || ''
      const genus = top.species?.genus?.scientificNameWithoutAuthor || ''
      const confidence = Math.round((top.score || 0) * 100)

      // Build alt names from remaining common names
      const altNames = commonNames.slice(1, 4).join(', ')

      const extra = medicinalDB[plantName.toLowerCase()] ||
        medicinalDB[scientific.toLowerCase()] || {
        description: `${plantName}${altNames ? ` (also known as ${altNames})` : ''} is a plant from the ${family || genus || 'unknown'} family. It was identified by PlantNet AI with ${confidence}% confidence.`,
        medicinal_uses: [
          'Traditional uses vary by region and culture',
          'Commonly used in folk medicine practices',
          'Consult a qualified herbalist for specific applications',
        ],
        preparation: `Fresh or dried ${plantName.toLowerCase()} parts can be prepared as teas, tinctures, or topical applications depending on the intended use. Always consult a herbalist before preparation.`,
        safety: 'Safety profile not fully documented. Do not consume without guidance from a qualified herbalist or healthcare provider. Keep away from children.',
        is_toxic: false,
      }

      setResult({
        name: plantName,
        scientific_name: scientific,
        confidence,
        family: family || genus,
        ...extra,
      } as PlantResult)

    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Unknown error'
      setError(`Could not identify this plant: ${msg}. Try a clearer, well-lit photo with the plant centred and in focus.`)
    } finally {
      setLoading(false)
    }
  }

  const reset = () => {
    setImage(null); setFile(null); setResult(null); setError(null)
    if (fileInputRef.current) fileInputRef.current.value = ''
  }

  return (
    <div className="min-h-screen" style={{ background: 'linear-gradient(180deg, #f5f2ed 0%, #f8f6f2 100%)' }}>
      {/* Header */}
      <div className="bg-forest py-20 px-4 relative overflow-hidden">
        <div className="absolute inset-0 opacity-10 pointer-events-none"
          style={{ backgroundImage: 'radial-gradient(circle, rgba(255,215,0,0.4) 1px, transparent 1px)', backgroundSize: '40px 40px' }} />
        <div className="text-center relative">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full mb-4"
            style={{ background: 'rgba(34,160,80,0.15)', border: '1px solid rgba(34,160,80,0.3)' }}>
            <Microscope className="w-3.5 h-3.5 text-green-400" />
            <span className="text-xs font-body uppercase tracking-widest text-green-400">Powered by PlantNet AI</span>
          </div>
          <h1 className="font-display text-4xl lg:text-5xl font-bold text-white mb-4">
            Plant <span className="gold-text">Identifier</span>
          </h1>
          <p className="font-body max-w-xl mx-auto" style={{ color: 'rgba(187,244,210,0.75)' }}>
            Snap or upload a photo of any plant. We will identify it and reveal its medicinal properties, uses, and preparation methods.
          </p>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 py-12">

        {/* UPLOAD ZONE */}
        {!image && (
          <div onDrop={handleDrop} onDragOver={e => e.preventDefault()}
            onClick={() => fileInputRef.current?.click()}
            className="cursor-pointer group relative overflow-hidden rounded-3xl transition-all"
            style={{ background: 'linear-gradient(160deg, #071a0e, #0a3d1f)', border: '2px dashed rgba(34,160,80,0.35)', minHeight: 320, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <div className="absolute inset-0 opacity-10"
              style={{ backgroundImage: 'radial-gradient(circle, rgba(255,215,0,0.4) 1px, transparent 1px)', backgroundSize: '30px 30px' }} />
            <div className="scan-corner scan-corner-tl" />
            <div className="scan-corner scan-corner-tr" />
            <div className="scan-corner scan-corner-bl" />
            <div className="scan-corner scan-corner-br" />
            <div className="absolute inset-0 rounded-3xl opacity-0 group-hover:opacity-100 transition-opacity"
              style={{ background: 'radial-gradient(circle at center, rgba(34,160,80,0.08), transparent 70%)' }} />
            <div className="text-center relative z-10 py-12 px-8">
              <div className="relative inline-block mb-6">
                <div className="w-24 h-24 rounded-3xl flex items-center justify-center mx-auto"
                  style={{ background: 'linear-gradient(135deg, #145a2e, #22a050)', boxShadow: '0 16px 40px rgba(34,160,80,0.4)' }}>
                  <Camera className="w-12 h-12 text-white" />
                </div>
                <div className="absolute -top-1 -right-1 w-7 h-7 rounded-full flex items-center justify-center"
                  style={{ background: 'linear-gradient(135deg, #ffd700, #b87800)', boxShadow: '0 4px 12px rgba(255,215,0,0.5)' }}>
                  <Upload className="w-3.5 h-3.5 text-green-900" />
                </div>
              </div>
              <h3 className="font-display text-2xl font-bold text-white mb-3">Upload a Plant Photo</h3>
              <p className="font-body text-sm mb-6" style={{ color: 'rgba(187,244,210,0.6)' }}>Click to browse or drag and drop · JPG, PNG up to 10MB</p>
              <div className="btn-gold inline-flex items-center gap-2 text-sm">
                <Upload className="w-4 h-4" /> Choose Photo
              </div>
              <div className="mt-6 flex flex-wrap justify-center gap-3">
                {['Clear photo', 'Good lighting', 'Leaf or flower', 'Close-up'].map(tip => (
                  <span key={tip} className="text-xs font-body px-3 py-1 rounded-full"
                    style={{ background: 'rgba(255,255,255,0.06)', color: 'rgba(187,244,210,0.6)', border: '1px solid rgba(255,255,255,0.08)' }}>
                    ✓ {tip}
                  </span>
                ))}
              </div>
            </div>
          </div>
        )}

        <input ref={fileInputRef} type="file" accept="image/*" onChange={handleFileChange} className="hidden" />

        {/* DASHBOARD after image upload */}
        {image && (
          <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">

            {/* LEFT: Plant image panel */}
            <div className="lg:col-span-2">
              <div className="rounded-2xl overflow-hidden"
                style={{ background: 'linear-gradient(160deg, #071a0e, #0a3d1f)', border: '1px solid rgba(34,160,80,0.25)', boxShadow: '0 16px 48px rgba(0,0,0,0.2)' }}>
                <div className="relative">
                  <img src={image} alt="Plant to identify" className="w-full object-cover" style={{ maxHeight: 340, objectFit: 'cover' }} />
                  {loading && (
                    <div className="absolute inset-0" style={{ background: 'rgba(10,61,31,0.5)' }}>
                      <div className="scan-line" />
                      <div className="scan-corner scan-corner-tl" /><div className="scan-corner scan-corner-tr" />
                      <div className="scan-corner scan-corner-bl" /><div className="scan-corner scan-corner-br" />
                      <div className="absolute inset-0 flex items-center justify-center">
                        <div className="text-center">
                          <Loader className="w-8 h-8 text-green-400 animate-spin mx-auto mb-2" />
                          <p className="text-green-300 text-xs font-body uppercase tracking-widest">Analyzing...</p>
                        </div>
                      </div>
                    </div>
                  )}
                  {result && (
                    <div className="absolute top-3 right-3 text-center px-3 py-2 rounded-xl"
                      style={{ background: 'linear-gradient(135deg, #ffd700, #b87800)', boxShadow: '0 4px 16px rgba(255,215,0,0.5)' }}>
                      <p className="font-display font-bold text-green-900 text-xl leading-none">{result.confidence}%</p>
                      <p className="text-green-900 text-xs font-body mt-0.5">match</p>
                    </div>
                  )}
                  {result && (
                    <div className="absolute bottom-0 left-0 right-0 p-4"
                      style={{ background: 'linear-gradient(to top, rgba(5,20,10,0.95), transparent)' }}>
                      <p className="font-display font-bold text-white text-lg leading-tight">{result.name}</p>
                      <p className="text-green-300 text-xs font-body italic mt-1">{result.scientific_name}</p>
                    </div>
                  )}
                </div>
                <div className="p-4 flex gap-3">
                  {!result && !loading && (
                    <button onClick={identifyPlant}
                      className="flex-1 flex items-center justify-center gap-2 font-body font-bold text-sm py-3 rounded-xl"
                      style={{ background: 'linear-gradient(135deg, #ffd700, #e6c300)', color: '#0a3d1f', boxShadow: '0 6px 20px rgba(255,215,0,0.4)' }}>
                      <Leaf className="w-4 h-4" /> Identify This Plant
                    </button>
                  )}
                  {result && (
                    <>
                      <button onClick={() => downloadPlantPDF(result)}
                        className="flex-1 flex items-center justify-center gap-2 font-body font-bold text-sm py-3 rounded-xl transition-all hover:scale-105"
                        style={{ background: 'linear-gradient(135deg, #ffd700, #e6c300)', color: '#0a3d1f', boxShadow: '0 4px 16px rgba(255,215,0,0.4)' }}>
                        <Download className="w-4 h-4" /> Save Report
                      </button>
                      <button onClick={reset}
                        className="flex items-center justify-center gap-2 font-body text-sm py-3 px-4 rounded-xl"
                        style={{ background: 'rgba(255,255,255,0.08)', color: 'rgba(255,255,255,0.7)', border: '1px solid rgba(255,255,255,0.1)' }}>
                        <RotateCcw className="w-4 h-4" /> New
                      </button>
                    </>
                  )}
                  {!result && !loading && (
                    <button onClick={reset} className="p-3 rounded-xl"
                      style={{ background: 'rgba(239,68,68,0.15)', color: '#f87171', border: '1px solid rgba(239,68,68,0.2)' }}>
                      <X className="w-4 h-4" />
                    </button>
                  )}
                </div>
              </div>
            </div>

            {/* RIGHT: Analysis panels */}
            <div className="lg:col-span-3 space-y-4">
              {!result && !error && !loading && (
                <div className="rounded-2xl p-8 text-center"
                  style={{ background: 'white', border: '1px solid rgba(255,215,0,0.2)', boxShadow: '0 4px 20px rgba(10,61,31,0.06)' }}>
                  <Leaf className="w-12 h-12 mx-auto mb-4" style={{ color: 'rgba(34,160,80,0.3)' }} />
                  <h3 className="font-display text-xl font-bold text-green-900 mb-2">Ready to Identify</h3>
                  <p className="font-body text-gray-500 text-sm mb-6">Your photo is uploaded. Press Identify to analyze its medicinal properties.</p>
                  <button onClick={identifyPlant} className="btn-gold inline-flex items-center gap-2">
                    <Leaf className="w-4 h-4" /> Identify This Plant
                  </button>
                </div>
              )}

              {loading && (
                <div className="rounded-2xl p-8 text-center"
                  style={{ background: 'linear-gradient(160deg, #071a0e, #0a3d1f)', border: '1px solid rgba(34,160,80,0.25)' }}>
                  <div className="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4"
                    style={{ background: 'rgba(34,160,80,0.2)', border: '1px solid rgba(34,160,80,0.3)' }}>
                    <Loader className="w-8 h-8 text-green-400 animate-spin" />
                  </div>
                  <h3 className="font-display text-xl font-bold text-white mb-2">Analyzing Plant...</h3>
                  <p className="font-body text-sm mb-6" style={{ color: 'rgba(187,244,210,0.6)' }}>Scanning against 300,000+ plant species</p>
                  <div className="space-y-2 text-left max-w-xs mx-auto">
                    {['Extracting visual features', 'Matching to database', 'Loading medicinal data'].map(step => (
                      <div key={step} className="flex items-center gap-3 text-sm font-body" style={{ color: 'rgba(187,244,210,0.6)' }}>
                        <Loader className="w-3.5 h-3.5 text-green-400 animate-spin flex-shrink-0" />
                        {step}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {error && (
                <div className="rounded-2xl p-5 flex items-start gap-3"
                  style={{ background: '#fff5f5', border: '1px solid #fecaca' }}>
                  <AlertCircle className="w-5 h-5 text-red-500 mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="text-red-700 font-body text-sm font-semibold mb-1">Identification Failed</p>
                    <p className="text-red-600 font-body text-sm">{error}</p>
                  </div>
                </div>
              )}

              {result && (
                <>
                  {result.is_toxic && (
                    <div className="rounded-2xl p-4 flex items-center gap-3"
                      style={{ background: '#fef2f2', border: '1px solid #fecaca' }}>
                      <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0" />
                      <p className="text-red-700 font-body text-sm font-semibold">This plant may be toxic. Do not consume without expert verification.</p>
                    </div>
                  )}

                  {/* Plant Profile — premium metric grid */}
                  <div className="wellness-card card-accent-top p-5 sm:p-6">
                    <div className="flex items-center justify-between mb-5">
                      <h3 className="font-display text-base sm:text-lg font-bold text-green-900" style={{ letterSpacing: '-0.01em' }}>Plant Profile</h3>
                      <span className="text-xs font-body px-2.5 py-1 rounded-full flex items-center gap-1.5"
                        style={{ background: 'rgba(34,160,80,0.1)', color: '#22a050', border: '1px solid rgba(34,160,80,0.22)' }}>
                        <CheckCircle className="w-3 h-3" /> Identified
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-2.5 sm:gap-3 mb-4">
                      {[
                        { icon: Leaf, label: 'Common Name', value: result.name, color: '#22a050' },
                        { icon: FlaskConical, label: 'Scientific Name', value: result.scientific_name || 'N/A', color: '#818cf8' },
                        { icon: Droplets, label: 'Plant Family', value: result.family || 'Unknown', color: '#38bdf8' },
                        { icon: Shield, label: 'Safety Status', value: result.is_toxic ? 'Toxic ⚠️' : 'Safe to study', color: result.is_toxic ? '#ef4444' : '#22a050' },
                      ].map(item => (
                        <div key={item.label} className="rounded-xl p-3 transition-all hover:scale-[1.02]"
                          style={{
                            background: `linear-gradient(140deg, ${item.color}10 0%, ${item.color}05 100%)`,
                            border: `1px solid ${item.color}28`,
                            boxShadow: `0 2px 8px ${item.color}10`,
                          }}>
                          <div className="flex items-center gap-1.5 mb-1.5">
                            <div className="w-6 h-6 rounded-md flex items-center justify-center"
                              style={{ background: item.color + '22', border: `1px solid ${item.color}40` }}>
                              <item.icon className="w-3 h-3" style={{ color: item.color }} />
                            </div>
                            <span className="text-[10px] font-body uppercase tracking-[0.16em] font-semibold" style={{ color: item.color }}>{item.label}</span>
                          </div>
                          <p className="font-body font-semibold text-green-900 text-sm leading-tight line-clamp-1">{item.value}</p>
                        </div>
                      ))}
                    </div>
                    <p className="font-body text-sm leading-relaxed pt-3 border-t" style={{ color: '#5b6f5f', borderColor: 'rgba(34,160,80,0.1)' }}>
                      {result.description}
                    </p>
                  </div>

                  {/* Medicinal Uses */}
                  <div className="wellness-card card-accent-top p-5 sm:p-6">
                    <h3 className="font-display text-base sm:text-lg font-bold text-green-900 mb-4" style={{ letterSpacing: '-0.01em' }}>Medicinal Uses</h3>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 sm:gap-2.5">
                      {result.medicinal_uses.map((use, i) => (
                        <div key={use} className="flex items-center gap-2.5 rounded-xl px-3 py-2.5 transition-all hover:scale-[1.02]"
                          style={{
                            background: i % 2 === 0 ? 'linear-gradient(140deg, rgba(34,160,80,0.10), rgba(34,160,80,0.04))' : 'linear-gradient(140deg, rgba(255,215,0,0.10), rgba(255,215,0,0.04))',
                            border: `1px solid ${i % 2 === 0 ? 'rgba(34,160,80,0.20)' : 'rgba(255,215,0,0.25)'}`,
                          }}>
                          <div className="w-2 h-2 rounded-full flex-shrink-0" style={{ background: i % 2 === 0 ? '#22a050' : '#d4a000', boxShadow: `0 0 8px ${i % 2 === 0 ? 'rgba(34,160,80,0.6)' : 'rgba(255,215,0,0.5)'}` }} />
                          <p className="text-sm font-body text-green-900 font-medium">{use}</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Preparation Guide — dark card like Zolve Smart Analysis */}
                  <div className="rounded-2xl p-5"
                    style={{ background: 'linear-gradient(160deg, #071a0e, #0a3d1f)', border: '1px solid rgba(255,215,0,0.15)', boxShadow: '0 8px 32px rgba(0,0,0,0.15)' }}>
                    <div className="flex items-center gap-2 mb-3">
                      <div className="w-8 h-8 rounded-lg flex items-center justify-center"
                        style={{ background: 'rgba(255,215,0,0.15)', border: '1px solid rgba(255,215,0,0.3)' }}>
                        <Sun className="w-4 h-4" style={{ color: '#ffd700' }} />
                      </div>
                      <h3 className="font-display text-base font-bold text-white">Preparation Guide</h3>
                    </div>
                    <p className="font-body text-sm leading-relaxed" style={{ color: 'rgba(187,244,210,0.8)' }}>{result.preparation}</p>
                  </div>

                  {/* Safety */}
                  <div className="rounded-2xl p-4 flex items-start gap-3"
                    style={{ background: '#fffbeb', border: '1px solid rgba(253,211,77,0.5)' }}>
                    <AlertCircle className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" />
                    <div>
                      <p className="font-display text-sm font-bold text-amber-800 mb-1">Safety Information</p>
                      <p className="text-amber-700 font-body text-sm leading-relaxed">{result.safety}</p>
                    </div>
                  </div>
                </>
              )}
            </div>
          </div>
        )}

        {/* Tips — shown when no image */}
        {!image && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mt-8">
            {[
              { icon: Camera, title: 'Best Photo Tips', accent: '#22a050', tips: ['Focus on a single leaf or flower', 'Use good natural lighting', 'Avoid blurry or dark photos'] },
              { icon: Leaf, title: 'What We Identify', accent: '#ffd700', tips: ['500,000+ plant species', 'Herbs, flowers, trees and shrubs', 'Medicinal and toxic plants'] },
              { icon: Shield, title: 'Safety First', accent: '#22a050', tips: ['Always verify with a herbalist', 'Never consume unknown plants', 'Check for toxicity warnings'] },
            ].map(card => (
              <div key={card.title} className="group wellness-card card-accent-top p-6 sm:p-7">
                <div className="w-12 h-12 rounded-2xl flex items-center justify-center mb-4 transition-transform duration-500 group-hover:scale-110 group-hover:rotate-[-4deg]"
                  style={{
                    background: card.accent === '#ffd700' ? 'linear-gradient(135deg, #b87800, #ffd700)' : 'linear-gradient(135deg, #145a2e, #22a050)',
                    boxShadow: `0 8px 22px ${card.accent}40, inset 0 1px 0 rgba(255,255,255,0.25)`,
                  }}>
                  <card.icon className="w-5 h-5" style={{ color: card.accent === '#ffd700' ? '#0a3d1f' : 'white' }} />
                </div>
                <h4 className="font-display text-base sm:text-lg font-bold text-green-900 mb-3" style={{ letterSpacing: '-0.01em' }}>{card.title}</h4>
                <ul className="space-y-2">
                  {card.tips.map(t => (
                    <li key={t} className="flex items-start gap-2 text-sm font-body" style={{ color: '#5b6f5f' }}>
                      <span className="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0" style={{ background: card.accent === '#ffd700' ? '#d4a000' : '#22a050' }} />
                      {t}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
